### ISSUE TITLE
Only store meta data once

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#180]
- [ ] Remove type from the VariableDummy objects, as it derives from the equations not the variable
- [x] Remove all but type from the graph
- [ ] Add some documentation / example code to the Model docstring

See #149

**Comment by MichaelClerx** [comment]
OK leaving this for now
