### ISSUE TITLE
Model manipulation

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#21]
As of Sept 16 2019 I (@skeating ) have broken up the remaining issues here into smaller issues:
#80 #81 #82 #83 #84 
Any unchecked item below reference the issue that now also contains it.

Initial thoughts, to be expanded...

* [x] Parsing of simple mathematical systems (cf #22) - Issues copied to #80
* [x] Parsing of realistic models - Issues copied to #82
* [x] Analysing systems of equations - Issues copied to #81
* [x] Interface needed for model manipulation  - Issues copied to #83
* [x] Interface needed for code generation - Issues copied to #84

Tasks:
- [x] @jonc125 to create initial sample CellML files - see #22

**Comment by jonc125** [comment]
The easiest way to test the parsing parts of this is probably to simulate the parsed models (cf #2) which potentially also requires the code generation aspects. Need to discuss (tomorrow!) how much overlap/integration we want between these tools. See also https://github.com/ModellingWebLab/project_issues/issues/12 and discussions about [Melodee](https://github.com/LLNL/melodee).

**Comment by jonc125** [comment]
@tamuri can you tick off in the description the items now done?

**Comment by tamuri** [comment]
ticked off a few more items

**Comment by MichaelClerx** [comment]
Shall we remove the sub-items here for every section that's now got its own overview ticket?

**Comment by jonc125** [comment]
We could remove the detailed text from here, but I'd keep the links to the individual issues.

**Comment by MauriceHendrix** [comment]
By the way the way the code for chaste codegen does it at the moment is without replacing variables.
say V is in Volt then:
- I find V and multiply by conversion factor
- use subs on other equations to substitute vs for 1/factor * V

It's probably less easy/safe but it does get round any issues with ordering of the variables
