### ISSUE TITLE
Interface for Model manipulation

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#83]
Remaining items from this section of #21 

* [x] Look up variable(s) by RDF annotation
    * Actually by cmeta:id - RDF library will handle finding the ID from property + object
    * No variable found - can be OK or not (chosen by caller)
    * One variable found
    * Multiple variables found - can be OK or not (chosen by caller)
* [x] Look up RDF annotation(s) for a given variable
* [x] Get the free variable
* [x] Iterate over state variables
* [x] Iterate over all variables
* [x] Get the equation defining a variable / derivative
    * [x] Get the RHS of the equation
* [x] Get variables referenced by an equation
* [x] Get equations needed to compute a set of variables, recursively
    * [x] Where 'variables' can include ODE RHSs, i.e. the definition of a derivative
* [x] Given an equation, tell easily if it's an ODE or simple assignment
    * [x] Get the variable assigned to, state var, or free var
* [x] Add a variable (optionally with units, annotations) #172 allows adding a variable with units 
    * [x] Add an annotation for a variable
    * [x] Units may be unknown when variable is first added, and calculated later from its definition. We need to be able to find all such variables easily.
* [x] Remove an equation from the system #171 adds this functionality
* [x] Add an equation to the system #118
    * [x] Variable names in new equations can be things like oxmeta:membrane_voltage - these need to be mapped to names suitable for code generation at some point, and identified with other variables having that annotation #118
* [ ] Replace part of an equation
    * [ ] E.g. to replace an 'original_definition' symbol with the equation originally defining it
    * [ ] This needs to be a 'clone' of the inserted equation
* [ ] Allow 'special' operations, so we can represent 'linear interpolation on a data file'
* [x] Handle time units conversion issue (#77 should deal with this)
    * RHS gets assigned to new variable with original units; change references to original derivative to this new variable; add another version of this variable with desired units, assigned from this one; use that to define the ODE.
* [x] Handle [state] variable units conversion (#77 should deal with this)
    * See _replace_variable logic, and perhaps _add_converted_variable - should be able to merge these
* [x] Construct an equation on the fly
* [x] Track which equations were added to the system
* [ ] Redo model consistency checks & units conversions after all modifications done

**Comment by MichaelClerx** [comment]
What's "replace part of an equation" and why do we want to do that?

**Comment by MichaelClerx** [comment]
I think we've done a lot of the unchecked ones, @jonc125 ?
A few could also be crossed out, as they're more part of chaste-codegen / fc? For example "linear interpolation on a data file" or "Redo model consistency checks & units conversions after all modifications done" ?

**Comment by jonc125** [comment]
Remaining items don't need special support here I think; can be done in weblab-fc.
